module.exports = {
    angular: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts',         dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts',      dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/Simple-Line-Icons/fonts', dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'src/fonts',   dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'src/api',     dest: "angular/api"},
            {expand: true, src: "**", cwd: 'src/l10n',    dest: "angular/l10n"},
            {expand: true, src: "**", cwd: 'src/img',     dest: "angular/img"},
            {expand: true, src: "**", cwd: 'src/js',      dest: "angular/js"},
            {expand: true, src: "**", cwd: 'src/tpl',     dest: "angular/tpl"},

            {src: 'bower_components/echarts/dist/echarts.min.js', dest: "angular/lib/echarts/dist/echarts.min.js"},
            {src: 'bower_components/echarts/dist/extension/bmap.min.js ', dest: "angular/lib/echarts/dist/extension/bmap.min.js"},
            {src: 'bower_components/angular-echarts/dist/angular-echarts.min.js', dest: "angular/lib/angular-echarts/angular-echarts.min.js"},
            {src: 'bower_components/easy-pie-chart/dist/angular.easypiechart.min.js', dest: "angular/lib/easy-pie-chart/angular.easypiechart.min.js"},
            {src: 'bower_components/easy-pie-chart/dist/jquery.easypiechart.js', dest: "angular/lib/jquery.easy-pie-chart/dist/jquery.easypiechart.js"},
            {src: 'bower_components/jquery.sparkline/dist/jquery.sparkline.min.js', dest: "angular/lib/jquery.sparkline/jquery.sparkline.min.js"},
            {src: 'bower_components/flot/jquery.flot.js', dest: "angular/lib/flot/jquery.flot.js"},
            {src: 'bower_components/flot/jquery.flot.pie.js', dest: "angular/lib/flot/jquery.flot.pie.js"},
            {src: 'bower_components/flot/jquery.flot.resize.js', dest: "angular/lib/flot/jquery.flot.resize.js"},
            {src: 'bower_components/flot.tooltip/js/jquery.flot.tooltip.js', dest: "angular/lib/flot.tooltip/js/jquery.flot.tooltip.js"},
            {src: 'bower_components/flot.orderbars/js/jquery.flot.orderBars.js', dest: "angular/lib/flot.orderbars/js/jquery.flot.orderBars.js"},
            {src: 'bower_components/flot-spline/js/jquery.flot.spline.js', dest: "angular/lib/flot-spline/js/jquery.flot.spline.js"},
            {src: 'bower_components/moment/moment.js', dest: "angular/lib/moment/moment.js"},
            {src: 'bower_components/slimscroll/jquery.slimscroll.min.js', dest: "angular/lib/slimscroll/jquery.slimscroll.min.js"},
            {src: 'bower_components/html5sortable/jquery.sortable.js', dest: "angular/lib/html5sortable/jquery.sortable.js"},
            {src: 'bower_components/nestable/jquery.nestable.js', dest: "angular/lib/nestable/jquery.nestable.js"},
            {src: 'bower_components/nestable/jquery.nestable.css', dest: "angular/lib/nestable/jquery.nestable.css"},
            {src: 'bower_components/bootstrap-filestyle/src/bootstrap-filestyle.js', dest: "angular/lib/bootstrap-filestyle/src/bootstrap-filestyle.js"},
            {src: 'bower_components/bootstrap-slider/bootstrap-slider.js', dest: "angular/lib/bootstrap-slider/bootstrap-slider.js"},
            {src: 'bower_components/bootstrap-slider/bootstrap-slider.css', dest: "angular/lib/bootstrap-slider/bootstrap-slider.css"},
            {src: 'bower_components/chosen/chosen.jquery.min.js', dest: "angular/lib/chosen/chosen.jquery.min.js"},
            {src: 'bower_components/bootstrap-chosen/bootstrap-chosen.css', dest: "angular/lib/bootstrap-chosen/bootstrap-chosen.css"},
            {src: 'bower_components/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js', dest: "angular/lib/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"},
            {src: 'bower_components/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css', dest: "angular/lib/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css"},
            {src: 'bower_components/bootstrap-wysiwyg/bootstrap-wysiwyg.js', dest: "angular/lib/bootstrap-wysiwyg/bootstrap-wysiwyg.js"},
            {src: 'bower_components/bootstrap-wysiwyg/external/jquery.hotkeys.js', dest: "angular/lib/bootstrap-wysiwyg/external/jquery.hotkeys.js"},
            {src: 'bower_components/datatables/media/js/jquery.dataTables.min.js', dest: "angular/lib/datatables/media/js/jquery.dataTables.min.js"},
            {src: 'bower_components/plugins/integration/bootstrap/3/dataTables.bootstrap.js', dest: "angular/lib/plugins/integration/bootstrap/3/dataTables.bootstrap.js"},
            {src: 'bower_components/plugins/integration/bootstrap/3/dataTables.bootstrap.css', dest: "angular/lib/plugins/integration/bootstrap/3/dataTables.bootstrap.css"},
            {src: 'bower_components/bower-jvectormap/jquery-jvectormap-1.2.2.min.js', dest: "angular/lib/bower-jvectormap/jquery-jvectormap-1.2.2.min.js"},
            {src: 'bower_components/bower-jvectormap/jquery-jvectormap-world-mill-en.js', dest: "angular/lib/bower-jvectormap/jquery-jvectormap-world-mill-en.js"},
            {src: 'bower_components/bower-jvectormap/jquery-jvectormap-1.2.2.css', dest: "angular/lib/bower-jvectormap/jquery-jvectormap-1.2.2.css"},
            {src: 'bower_components/footable/dist/footable.all.min.js', dest: "angular/lib/footable/dist/footable.all.min.js"},
            {src: 'bower_components/footable/css/footable.core.css', dest: "angular/lib/footable/css/footable.core.css"},
            {src: 'bower_components/fullcalendar/dist/fullcalendar.min.js', dest: "angular/lib/fullcalendar/dist/fullcalendar.min.js"},
            {src: 'bower_components/fullcalendar/dist/fullcalendar.css', dest: "angular/lib/fullcalendar/dist/fullcalendar.css"},
            {src: 'bower_components/bootstrap-daterangepicker/daterangepicker.js', dest: "angular/lib/bootstrap-daterangepicker/daterangepicker.js"},
            {src: 'bower_components/bootstrap-daterangepicker/daterangepicker-bs3.css', dest: "angular/lib/bootstrap-daterangepicker/daterangepicker-bs3.css"},
            {src: 'bower_components/bootstrap-tagsinput/dist/bootstrap-tagsinput.js', dest: "angular/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.js"},
            {src: 'bower_components/bootstrap-tagsinput/dist/bootstrap-tagsinput.css', dest: "angular/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css"},
            {src: 'bower_components/ng-grid/build/ng-grid.min.js', dest: "angular/lib/ng-grid/build/ng-grid.min.js"},
            {src: 'bower_components/ng-grid/build/ng-grid.min.css', dest: "angular/lib/ng-grid/build/ng-grid.min.css"},
            {src: 'bower_components/angular-ui-grid/ui-grid.min.js', dest: "angular/lib/angular-ui-grid/ui-grid.min.js"},
            {src: 'bower_components/angular-ui-grid/ui-grid.min.css', dest: "angular/lib/angular-ui-grid/ui-grid.min.css"},
            {src: 'bower_components/angular-ui-select/dist/select.min.js', dest: "angular/lib/angular-ui-select/dist/select.min.js"},
            {src: 'bower_components/angular-ui-select/dist/select.min.css', dest: "angular/lib/angular-ui-select/dist/select.min.css"},
            {src: 'bower_components/angular-file-upload/angular-file-upload.min.js', dest: "angular/lib/angular-file-upload/angular-file-upload.min.js"},
            {src: 'bower_components/angular-ui-calendar/src/calendar.js', dest: "angular/lib/angular-ui-calendar/src/calendar.js"},
            {src: 'bower_components/angularjs-toaster/toaster.js', dest: "angular/lib/angularjs-toaster/toaster.js"},
            {src: 'bower_components/angularjs-toaster/toaster.css', dest: "angular/lib/angularjs-toaster/toaster.css"},
            {src: 'bower_components/textAngular/dist/textAngular-sanitize.min.js', dest: "angular/lib/textAngular/dist/textAngular-sanitize.min.js"},
            {src: 'bower_components/textAngular/dist/textAngular.min.js', dest: "angular/lib/textAngular/dist/textAngular.min.js"},
            {src: 'bower_components/venturocket-angular-slider/build/angular-slider.min.js', dest: "angular/lib/venturocket-angular-slider/build/angular-slider.min.js"},
            {src: 'bower_components/videogular/videogular.min.js', dest: "angular/lib/videogular/videogular.min.js"},
            {src: 'bower_components/videogular-controls/controls.min.js', dest: "angular/lib/videogular-controls/controls.min.js"},
            {src: 'bower_components/videogular-buffering/buffering.min.js', dest: "angular/lib/videogular-buffering/buffering.min.js"},
            {src: 'bower_components/videogular-overlay-play/overlay-play.min.js', dest: "angular/lib/videogular-overlay-play/overlay-play.min.js"},
            {src: 'bower_components/videogular-poster/poster.min.js', dest: "angular/lib/videogular-poster/poster.min.js"},
            {src: 'bower_components/videogular-ima-ads/ima-ads.min.js', dest: "angular/lib/videogular-ima-ads/ima-ads.min.js"},
            {src: 'bower_components/angular-xeditable/dist/js/xeditable.min.js', dest: "angular/lib/angular-xeditable/dist/js/xeditable.min.js"},
            {src: 'bower_components/angular-xeditable/dist/js/xeditable.min.css', dest: "angular/lib/angular-xeditable/dist/js/xeditable.min.css"},
            {src: 'bower_components/angular-smart-table/dist/smart-table.min.js', dest: "angular/lib/angular-smart-table/dist/smart-table.min.js"},
            {src: 'bower_components/angular-bootstrap-nav-tree/dist/abn_tree.css', dest: "angular/lib/abnt/abntree.css"},
            {src: 'bower_components/angular-bootstrap-nav-tree/dist/abn_tree_directive.js', dest: "angular/lib/abnt/abntree.js"},
            {src: 'bower_components/Highcharts-4.2.5/js/highcharts.js', dest : 'angular/lib/Highcharts-4.2.5/highcharts.js'},
            {src: 'bower_components/highcharts-ng/dist/highcharts-ng.js', dest : 'angular/lib/highcharts-ng/highcharts-ng.js'},
            {src: 'bower_components/screenfull/dist/screenfull.min.js', dest : 'angular/lib/screenfull/screenfull.min.js'},
            {src: 'bower_components/angular-busy/dist/angular-busy.min.js', dest : 'angular/lib/angular-busy/angular-busy.min.js'},
            {src: 'bower_components/angular-busy/dist/angular-busy.min.css', dest : 'angular/lib/angular-busy/angular-busy.min.css'},
            {src: 'bower_components/jquery/dist/jquery.min.js', dest : 'angular/lib/jquery/jquery.min.js'},
            {src: 'bower_components/angular/angular.min.js', dest : 'angular/lib/angular/angular.min.js'},
            {src: 'bower_components/angular-bootstrap/ui-bootstrap.min.js', dest : 'angular/lib/angular-bootstrap/ui-bootstrap.min.js'},
            {src: 'bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js', dest : 'angular/lib/angular-bootstrap/ui-bootstrap-tpls.min.js'},
            {src: 'bower_components/angularjs-toaster/toaster.min.js', dest : 'angular/lib/angularjs-toaster/toaster.min.js'},
            {src: 'bower_components/bootstrap-switch/dist/js/bootstrap-switch.min.js', dest : 'angular/lib/bootstrap-switch/js/bootstrap-switch.min.js'},
            {src: 'bower_components/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css', dest : 'angular/lib/bootstrap-switch/css/bootstrap-switch.min.css'},
            {src: 'bower_components/angular-bootstrap-switch/dist/angular-bootstrap-switch.min.js', dest : 'angular/lib/angular-bootstrap-switch/angular-bootstrap-switch.min.js'},
            {src: 'bower_components/angularjs-slider/dist/rzslider.min.css', dest : 'angular/lib/angularjs-slider/rzslider.min.css'},
            {src: 'bower_components/angularjs-slider/dist/rzslider.min.js', dest : 'angular/lib/angularjs-slider/rzslider.min.js'},
            {src: 'bower_components/ngImgCrop/compile/minified/ng-img-crop.js', dest : 'angular/lib/ngImgCrop/compile/minified/ng-img-crop.js'},
            {src: 'bower_components/ngImgCrop/compile/minified/ng-img-crop.css', dest : 'angular/lib/ngImgCrop/compile/minified/ng-img-crop.css'},
            {src: 'bower_components/ng-file-upload/ng-file-upload-all.min.js', dest : 'angular/lib/ng-file-upload/ng-file-upload-all.min.js'},
            {src: ['src/lib/ckplayer/ckplayer.js'], dest : 'angular/lib/ckplayer/ckplayer.js'},
            {src: ['src/lib/ckplayer/ckplayer.swf'], dest : 'angular/lib/ckplayer/ckplayer.swf'},
            {src: ['src/lib/ckplayer/ckplayer.xml'], dest : 'angular/lib/ckplayer/ckplayer.xml'},
            {src: ['src/lib/ckplayer/language.xml'], dest : 'angular/lib/ckplayer/language.xml'},
            {src: ['src/lib/ckplayer/m3u8.swf'], dest : 'angular/lib/ckplayer/m3u8.swf'},
            {src: ['src/lib/ckplayer/monitor.swf'], dest : 'angular/lib/ckplayer/monitor.swf'},
            {src: ['src/lib/ckplayer/related.xml'], dest : 'angular/lib/ckplayer/related.xml'},
            {src: ['src/lib/ckplayer/share.xml'], dest : 'angular/lib/ckplayer/share.xml'},
            {src: ['src/lib/ckplayer/style.swf'], dest : 'angular/lib/ckplayer/style.swf'},

            {src: 'src/index.min.html', dest : 'angular/index.html'}
        ]
    },
    html: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts',         dest: "html/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts',      dest: "html/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/Simple-Line-Icons/fonts', dest: "html/fonts"},
            {expand: true, src: '**', cwd:'src/fonts/', dest: 'html/fonts/'},
            {expand: true, src: "**", cwd: 'src/api',     dest: "html/api"},
            {expand: true, src: '**', cwd:'src/img/', dest: 'html/img/'},
            {expand: true, src: '*.css', cwd:'src/css/', dest: 'html/css/'},
            {expand: true, src: '**', cwd:'swig/js/', dest: 'html/js/'}
        ]
    },
    landing: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts',         dest: "landing/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts',      dest: "landing/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/Simple-Line-Icons/fonts', dest: "landing/fonts"},
            {expand: true, src:'**', cwd:'src/fonts/', dest: 'landing/fonts/'},
            {expand: true, src:'*.css', cwd:'src/css/', dest: 'landing/css/'},
            {src:'html/css/app.min.css', dest: 'landing/css/app.min.css'}
        ]
    }

};
